### ISSUE TITLE
chimera (MAC OS)

### ISSUE THREAD

**Issue by jingyile** [insilichem/gpathfinder#6]
I have installed chimera through the dmg file, how should I configure the environment variables?

**Comment by jingyile** [comment]
this is my current code :
```
export CHIMERA=/Users/dabuyingtukoushui/Desktop/Vacation/GPathFinder/Chimera.app/Contents/MacOS/chimera

export CHIMERADIR=/Users/dabuyingtukoushui/Desktop/Vacation/GPathFinder/Chimera.app
```

**Comment by jingyile** [comment]
this is the error messages:
```

Traceback (most recent call last):
  File "/Users/dabuyingtukoushui/opt/anaconda3/envs/gpathfinder/bin/gpath", line 10, in <module>
    sys.exit(cli())
  File "/Users/dabuyingtukoushui/opt/anaconda3/envs/gpathfinder/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dabuyingtukoushui/opt/anaconda3/envs/gpathfinder/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/dabuyingtukoushui/opt/anaconda3/envs/gpathfinder/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dabuyingtukoushui/opt/anaconda3/envs/gpathfinder/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dabuyingtukoushui/opt/anaconda3/envs/gpathfinder/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/dabuyingtukoushui/opt/anaconda3/envs/gpathfinder/lib/python2.7/site-packages/gpath/cli/gpath_cli.py", line 121, in run
    load_chimera()
  File "/Users/dabuyingtukoushui/opt/anaconda3/envs/gpathfinder/lib/python2.7/site-packages/gpath/cli/gpath_cli.py", line 75, in load_chimera
    pychimera.enable_chimera()
  File "/Users/dabuyingtukoushui/opt/anaconda3/envs/gpathfinder/lib/python2.7/site-packages/pychimera/core.py", line 51, in enable_chimera
    import chimera
ImportError: No module named chimera
```

**Comment by josan82** [comment]
Dear @jingyile,

I think I were able to reproduce your issue with the installation in MAC OS. I solved it by adding this line (containing the /bin of the Chimera app) to my PATH variable:

`/Applications/Chimera.app/Contents/Resources/bin`

I also added it to my `.bash_profile` so I don't have to add it every time I open a terminal.

In [this link](https://uab-my.sharepoint.com/:v:/g/personal/2132358_uab_cat/ESitjZy69BJPmzkxVNStzOcBms_2ReiEH94i88eh7Ay68A) you have a video where I recorded my screen during the installation. You can see the error and the addition of the mentioned line from minute 1:40.

Please, let us know if with these instructions you solve the issue, so we can update the docs.

Thank you!

**Comment by jingyile** [comment]
> Dear @jingyile,
> 
> I think I were able to reproduce your issue with the installation in MAC OS. I solved it by adding this line (containing the /bin of the Chimera app) to my PATH variable:
> 
> `/Applications/Chimera.app/Contents/Resources/bin`
> 
> I also added it to my `.bash_profile` so I don't have to add it every time I open a terminal.
> 
> In [this link](https://uab-my.sharepoint.com/:v:/g/personal/2132358_uab_cat/ESitjZy69BJPmzkxVNStzOcBms_2ReiEH94i88eh7Ay68A) you have a video where I recorded my screen during the installation. You can see the error and the addition of the mentioned line from minute 1:40.
> 
> Please, let us know if with these instructions you solve the issue, so we can update the docs.
> 
> Thank you!

this is useful, thanks！
